# path: /tasks/assigned
get:
  operationId: getAssignedTaskList
  summary: List Assigned Tasks
  tags:
    - Task Management
  security:
    - ApiKeyAuth: []
  responses:
    200:
      description: Success Response
    401:
      $ref: ../../components/responses/401.yml
    429:
      $ref: ../../components/responses/429.yml
    500:
      $ref: ../../components/responses/500.yml
