# path: /tasks/{task-id}
parameters:
  - $ref: ../../components/parameters/task-id.yml
get:
  operationId: getTask
  summary: Task Details
  tags:
    - Task Management
  security:
    - ApiKeyAuth: []
  responses:
    200:
      description: Success Response
      content:
        application/json:
          schema:
            $ref: https://softask-app.github.io/api-types/v1/types/task/new.json#
    401:
      $ref: ../../components/responses/401.yml
    404:
      $ref: ../../components/responses/404.yml
    429:
      $ref: ../../components/responses/429.yml
    500:
      $ref: ../../components/responses/500.yml
patch:
  operationId: updateTask
  summary: Update Task
  description: |
    Update user provided data for a task using a
    [JSON Patch](http://jsonpatch.com/) request.

    Fields that may be updated using this endpoint:

    ## `/name`

    * `"replace"`

    The `name` property text can be updated (via "replace"), but cannot
    otherwise be altered.  The updated value must conform to the type
    specification for the `name` field as defined in
    [the task JSON schema](https://softask-app.github.io/api-types/v1/types/task/full.json).

    ## `/description`

    * `"add"`
    * `"remove"`
    * `"replace"`

    The `description` property can be added, removed, or replaced as desired.
    When adding or replacing, the new value must conform to the type
    specification for the `description` field as defined in
    [the task JSON schema](https://softask-app.github.io/api-types/v1/types/task/full.json).

    ## `/assignees/{n|-}`

    * `"add"`
    * `"remove"`

    The `assignees` array may have elements added or removed from it, but must
    not be otherwise altered.

    Any entries added to the array must conform to the type specification for
    short user detail blocks as defined in
    [the user JSON schema](https://softask-app.github.io/api-types/v1/types/user/short.json).
  tags:
    - Task Management
  security:
    - ApiKeyAuth: []
  requestBody:
    description: JSON Patch Body
    content:
      application/json:
        schema:
          $ref: 'http://json.schemastore.org/json-patch#'
  responses:
    204:
      $ref: ../../components/responses/204.yml
    400:
      $ref: ../../components/responses/400.yml
    401:
      $ref: ../../components/responses/401.yml
    404:
      $ref: ../../components/responses/404.yml
    429:
      $ref: ../../components/responses/429.yml
    500:
      $ref: ../../components/responses/500.yml
delete:
  operationId: deleteTask
  summary: Delete Task
  tags:
    - Task Management
  security:
    - ApiKeyAuth: []
  responses:
    204:
      $ref: ../../components/responses/204.yml
    401:
      $ref: ../../components/responses/401.yml
    404:
      $ref: ../../components/responses/404.yml
    500:
      $ref: ../../components/responses/500.yml
