# path: /tasks/{task-id}/steps/{step-id}
get:
  operationId: getStep
  summary: View Step Details
  tags:
    - Step Management
  security:
    - ApiKeyAuth: []
  responses:
    200:
      description: Success Response
    401:
      $ref: ../../../../components/responses/401.yml
    404:
      $ref: ../../../../components/responses/404.yml
    429:
      $ref: ../../../../components/responses/429.yml
    500:
      $ref: ../../../../components/responses/500.yml
patch:
  operationId: updateStep
  summary: Update Step
  tags:
    - Step Management
  security:
    - ApiKeyAuth: []
  requestBody:
    description: JSON Patch Body
    content:
      application/json:
        schema:
          $ref: 'http://json.schemastore.org/json-patch#'
  responses:
    204:
      $ref: ../../../../components/responses/204.yml
    400:
      $ref: ../../../../components/responses/400.yml
    401:
      $ref: ../../../../components/responses/401.yml
    404:
      $ref: ../../../../components/responses/404.yml
    429:
      $ref: ../../../../components/responses/429.yml
    500:
      $ref: ../../../../components/responses/500.yml
delete:
  operationId: deleteStep
  summary: Delete Step
  tags:
    - Step Management
  security:
    - ApiKeyAuth: []
  responses:
    204:
      $ref: ../../../../components/responses/204.yml
    401:
      $ref: ../../../../components/responses/401.yml
    404:
      $ref: ../../../../components/responses/404.yml
    500:
      $ref: ../../../../components/responses/500.yml
